[package]
name = "lilypond-midi-entry"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
clap = { version = "3.2.22", features = ["derive"] }
enigo = "0.0.14"
midir = "0.8"
midly = "0.5"
